# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180504_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='active',
            options={'ordering': ('-publish',), 'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ('-publish',), 'verbose_name': '论文', 'verbose_name_plural': '论文'},
        ),
        migrations.AlterModelOptions(
            name='rsdirection',
            options={'verbose_name': '研究方向', 'verbose_name_plural': '研究方向'},
        ),
        migrations.AlterField(
            model_name='active',
            name='body',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='active',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_image', to=settings.FILER_IMAGE_MODEL, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='active',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='active',
            name='title',
            field=models.CharField(max_length=300, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='body',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=300, verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='rsdirection',
            name='body',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='rsdirection',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsdirection_image', to=settings.FILER_IMAGE_MODEL, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='rsdirection',
            name='title',
            field=models.CharField(max_length=300, verbose_name='名字'),
        ),
    ]
