# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monographs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monographs',
            options={'verbose_name': '论文及专著', 'verbose_name_plural': '论文及专著'},
        ),
        migrations.AlterField(
            model_name='monographs',
            name='name',
            field=models.CharField(max_length=300, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='monographs',
            name='publishing',
            field=models.CharField(blank=True, max_length=300, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='monographs',
            name='subject',
            field=models.CharField(max_length=300, verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='monographs',
            name='time',
            field=models.CharField(blank=True, max_length=300, verbose_name='时间'),
        ),
    ]
