# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180531_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=300, verbose_name='姓名'),
        ),
    ]
