# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20180531_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people_image', to=settings.FILER_IMAGE_MODEL, verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='people',
            name='interest',
            field=models.CharField(blank=True, max_length=300, verbose_name='研究兴趣'),
        ),
        migrations.AlterField(
            model_name='people',
            name='rsdirection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Rsdirection', verbose_name='方向'),
        ),
        migrations.AlterField(
            model_name='people',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='职称'),
        ),
    ]
