# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20180430_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': '科研项目', 'verbose_name_plural': '科研项目'},
        ),
        migrations.AlterField(
            model_name='research',
            name='name',
            field=models.CharField(max_length=200, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='research',
            name='orientation',
            field=models.CharField(blank=True, max_length=200, verbose_name='研究方向'),
        ),
        migrations.AlterField(
            model_name='research',
            name='projectorigin',
            field=models.CharField(blank=True, max_length=200, verbose_name='项目来源'),
        ),
        migrations.AlterField(
            model_name='research',
            name='rank',
            field=models.CharField(blank=True, max_length=200, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='research',
            name='time',
            field=models.CharField(blank=True, max_length=200, verbose_name='起止时间'),
        ),
    ]
