# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('adactivaty', '0002_adactivaty_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adactivaty',
            options={'verbose_name': '学术活动', 'verbose_name_plural': '学术活动'},
        ),
        migrations.AlterField(
            model_name='adactivaty',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adactivaty_image', to=settings.FILER_IMAGE_MODEL, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='adactivaty',
            name='title',
            field=models.CharField(max_length=300, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='adactivaty',
            name='year',
            field=models.CharField(blank=True, max_length=300, verbose_name='年份'),
        ),
    ]
