# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awards',
            options={'verbose_name': '成果获奖', 'verbose_name_plural': '成果获奖'},
        ),
        migrations.AlterField(
            model_name='awards',
            name='awardname',
            field=models.CharField(blank=True, max_length=300, verbose_name='获奖名称'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='company',
            field=models.CharField(blank=True, max_length=300, verbose_name='颁奖单位'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='projectname',
            field=models.CharField(blank=True, max_length=300, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='role',
            field=models.CharField(blank=True, max_length=300, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='time',
            field=models.CharField(max_length=300, verbose_name='获奖时间'),
        ),
    ]
